server:
  port: 8080

app:
  environment:
    name: PROD
  frontend:
    url: https://portfolio-frontend.aws.siample.dev
  websocket:
    allowed-origins: "https://portfolio-frontend.aws.siample.dev,https://portfolio-backend.aws.siample.dev,http://localhost:4200,http://localhost:8080"
